# version: '3.8'

networks:
  rede:
    driver: bridge

volumes:
  vol_api:
  vol_db:

services:
  db:
    container_name: container_db
    restart: always    
    env_file: ./.env
    # image: mysql:9.1.0
    # image: mysql:8.0
    # image: mysql:latest
    image: mysql:9.1.0
    volumes:
      - vol_db:/var/lib/mysql
    networks:
      - rede
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USER 
      MYSQL_PASSWORD: $DB_PASSWORD
      # MYSQL_ALLOW_EMPTY_PASSWORD: $DB_ALLOW_EMPTY_PASSWORD      
    ports: 
      - $DB_PORT_EXPOSE:$DB_PORT
    expose:
      - $DB_PORT_EXPOSE

  api:
    # command: --pid-file /var/run/mysqld
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /usr/src/api_vendas/api
    env_file: ./.env
    container_name: container_api
    restart: always
    depends_on:
      - db
    volumes:
      - vol_api:/var/lib/api
    image: node:22.12-alpine3.19
    networks:
      - rede
    environment:
      DB_HOST: db      
      DB_DATABASE: $DB_DATABASE
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
    ports: 
      - $PORT_EXPOSE:$PORT
    expose:
      - $PORT_EXPOSE

