# version: '3.8'

networks:
  rede:
    driver: bridge

services:
  db:
    container_name: cn_db
    env_file: ./.env
    image: mysql:9.1.0
    volumes:
      - vol_db:/var/lib/mysql
    networks:
      - rede
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ALLOW_EMPTY_PASSWORD: $DB_ALLOW_EMPTY_PASSWORD
    ports:
      - $DB_PORT_EXPOSE:$DB_PORT

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /usr/src/api_vendas/api
    env_file: ./.env
    container_name: cn_api
    depends_on:
      - db
    volumes:
      - vol_api:/var/lib/api
    networks:
      - rede
    environment:
      DB_HOST: db
      DB_DATABASE: $DB_DATABASE
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_PORT: $DB_PORT_EXPOSE
    ports:
      - $PORT_EXPOSE:$PORT
    restart: always

volumes:
  vol_api:
  vol_db:


